# Generated by Django 3.0.3 on 2023-04-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_related_name_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
